### ISSUE TITLE
create first prototype of tool

### ISSUE THREAD

**Issue by littlewhywhat** [littlewhywhat/raspberry-and-drawit#12]
- [ ] understand with how atrace is called by systrace - what parameters are passed
- [ ] create report similar to one that uses systrace (parse it to html if possible)
- [ ] wrap it into a tool prototype and put tool into build

**Comment by littlewhywhat** [comment]
for constructing arguments this code is used in atrace_agent.py
```python
# in def StartAgentTracing(self, config, timeout=None):
self._tracer_args = _construct_atrace_args(config,
                                               self._categories)
# ...
DEFAULT_CATEGORIES = 'sched,freq,gfx,view,dalvik,webview,'\
                     'input,disk,am,wm,rs,binder_driver'

def _construct_atrace_args(config, categories):
  """Builds the command used to invoke a trace process.
  Returns:
    A tuple where the first element is an array of command arguments, and
    the second element is a boolean which will be true if the command will
    stream trace data.
  """
  atrace_args = ATRACE_BASE_ARGS[:]

  if config.compress_trace_data:
    atrace_args.extend(['-z'])

  if (config.trace_time is not None) and (config.trace_time > 0):
    atrace_args.extend(['-t', str(config.trace_time)])

  if (config.trace_buf_size is not None) and (config.trace_buf_size > 0):
    atrace_args.extend(['-b', str(config.trace_buf_size)])

  elif 'sched' in categories:
    # 'sched' is a high-volume tag, double the default buffer size
    # to accommodate that
    atrace_args.extend(['-b', '4096'])
  extra_args = _construct_extra_atrace_args(config, categories)

  atrace_args.extend(extra_args)
  return atrace_args
```

**Comment by littlewhywhat** [comment]
atrace options
```
usage: atrace [options] [categories...]
options include:
  -a appname      enable app-level tracing for a comma separated list of cmdlines
  -b N            use a trace buffer size of N KB
  -c              trace into a circular buffer
  -f filename     use the categories written in a file as space-separated
                    values in a line
  -k fname,...    trace the listed kernel functions
  -n              ignore signals
  -s N            sleep for N seconds before tracing [default 0]
  -t N            trace for N seconds [defualt 5]
  -z              compress the trace dump
  --async_start   start circular trace and return immediatly
  --async_dump    dump the current contents of circular trace buffer
  --async_stop    stop tracing and dump the current contents of circular
                    trace buffer
  --stream        stream trace to stdout as it enters the trace buffer
                    Note: this can take significant CPU time, and is best
                    used for measuring things that are not affected by
                    CPU performance, like pagecache usage.
  --list_categories
                  list the available tracing categories
 -o filename      write the trace to the specified file instead
                    of stdout.
```

**Comment by littlewhywhat** [comment]
can't understand why tracer is nop...
```
TRACE:
# tracer: nop
#
# entries-in-buffer/entries-written: 3818/3818   #P:4
#
#                              _-----=> irqs-off
#                             / _----=> need-resched
#                            | / _---=> hardirq/softirq
#                            || / _--=> preempt-depth
#                            ||| /     delay
#           TASK-PID   CPU#  ||||    TIMESTAMP  FUNCTION
#              | |       |   ||||       |         |
          atrace-997   [001] ...1   653.751654: tracing_mark_write: trace_event_clock_sync: parent_ts=653.720215
          atrace-997   [001] ...1   653.751709: tracing_mark_write: trace_event_clock_sync: realtime_ts=1520953370166
          <idle>-0     [003] dnh3   653.753306: sched_wakeup: comm=kworker/u8:0 pid=988 prio=120 target_cpu=003
          <idle>-0     [003] d..3   653.753330: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=kworker/u8:0 next_pid=988 next_prio=120
    kworker/u8:0-988   [003] d..3   653.753361: sched_switch: prev_comm=kworker/u8:0 prev_pid=988 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [003] dnh3   653.753400: sched_wakeup: comm=kworker/u8:0 pid=988 prio=120 target_cpu=003
          <idle>-0     [003] d..3   653.753414: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=kworker/u8:0 next_pid=988 next_prio=120
    kworker/u8:0-988   [003] d..3   653.753432: sched_switch: prev_comm=kworker/u8:0 prev_pid=988 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [003] dnh3   653.753448: sched_wakeup: comm=kworker/u8:0 pid=988 prio=120 target_cpu=003
          <idle>-0     [003] d..3   653.753459: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=kworker/u8:0 next_pid=988 next_prio=120
    kworker/u8:0-988   [003] d..3   653.753524: sched_switch: prev_comm=kworker/u8:0 prev_pid=988 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [000] dnh3   653.753568: sched_wakeup: comm=sh pid=982 prio=120 target_cpu=000
          atrace-997   [001] d..3   653.753574: sched_switch: prev_comm=atrace prev_pid=997 prev_prio=120 prev_state=x ==> next_comm=rcu_sched next_pid=8 next_prio=120
          <idle>-0     [000] d..3   653.753590: sched_switch: prev_comm=swapper/0 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=sh next_pid=982 next_prio=120
       rcu_sched-8     [001] d..3   653.753603: sched_switch: prev_comm=rcu_sched prev_pid=8 prev_prio=120 prev_state=S ==> next_comm=swapper/1 next_pid=0 next_prio=120
          <idle>-0     [003] dnh3   653.754613: sched_wakeup: comm=kworker/u8:0 pid=988 prio=120 target_cpu=003
          <idle>-0     [003] d..3   653.754626: sched_switch: prev_comm=swapper/3 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=kworker/u8:0 next_pid=988 next_prio=120
              sh-982   [000] d..3   653.754638: sched_switch: prev_comm=sh prev_pid=982 prev_prio=120 prev_state=S ==> next_comm=swapper/0 next_pid=0 next_prio=120
    kworker/u8:0-988   [003] d..4   653.754646: sched_wakeup: comm=shell srvc 982 pid=983 prio=120 target_cpu=003
    kworker/u8:0-988   [003] d..3   653.754657: sched_switch: prev_comm=kworker/u8:0 prev_pid=988 prev_prio=120 prev_state=S ==> next_comm=shell srvc 982 next_pid=983 next_prio=120
          <idle>-0     [000] dnh3   653.754733: sched_wakeup: comm=adbd pid=134 prio=120 target_cpu=000
          <idle>-0     [000] d..3   653.754744: sched_switch: prev_comm=swapper/0 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=adbd next_pid=134 next_prio=120
  shell srvc 982-983   [003] d..3   653.754758: sched_switch: prev_comm=shell srvc 982 prev_pid=983 prev_prio=120 prev_state=S ==> next_comm=swapper/3 next_pid=0 next_prio=120
          <idle>-0     [001] dnh3   653.754944: sched_wakeup: comm=->host pid=980 prio=120 target_cpu=001
          <idle>-0     [001] d..3   653.754956: sched_switch: prev_comm=swapper/1 prev_pid=0 prev_prio=120 prev_state=R ==> next_comm=->host next_pid=980 next_prio=120
            adbd-134   [000] d..3   653.754986: sched_switch: prev_comm=adbd prev_pid=134 prev_prio=120 prev_state=S ==> next_comm=swapper/0 next_pid=0 next_prio=120
          <idle>-0     [003] dnh3   653.755135: sched_wakeup: comm=kworker/u8:0 pid=988 prio=120 target_cpu=003
```

**Comment by littlewhywhat** [comment]
```
rpi3:/ # cat sys/kernel/debug/tracing/current_tracer 
nop
```

**Comment by littlewhywhat** [comment]
rpi3:/ # cat sys/kernel/debug/tracing/available_tracers                                                                                                                                                            
blk function_graph wakeup_dl wakeup_rt wakeup irqsoff function nop

**Comment by littlewhywhat** [comment]
Can not put helloworld into build. Out.ninja place it in out/target/product/rpi3/obj/executables but it's not there after build. Mk is included but source is not recompiled by make systemimage.

**Comment by littlewhywhat** [comment]
i'll try to put it in rpi3.mk as 
```
PRODUCT_PACKAGES += \ 
    helloworld
```

**Comment by littlewhywhat** [comment]
build tries to compile but missing rc file or any rule to make it.
added helloworld.rc as:
```
service helloworld /system/bin/helloworld
```

**Comment by littlewhywhat** [comment]
now it works!

**Comment by littlewhywhat** [comment]
trying to use analogy from bugreportz

**Comment by littlewhywhat** [comment]
it works for target running. use this script:
```
python ./development/testrunner/runtest.py -x frameworks/native/cmds/greeter/
```
however there is another way to define test (host) but can't figure out how to run it.

**Comment by littlewhywhat** [comment]
the problem with host option that executable should be compiled for current processor x86. So I can not run executable that is produced by runtest.py on this machine. There should be some option for android build. However, I will leave it for issue #14.

**Comment by littlewhywhat** [comment]
Let's do the wrapper - there could be some issues with permissions and so on.

**Comment by littlewhywhat** [comment]
analyzing properties of android for atrace.rc
```
on property:persist.debug.atrace.boottrace=1
  start boottrace
```
made by https://android.googlesource.com/platform/system/core/+/f93db4b%5E%21/

properties are stored in files on device: https://stackoverflow.com/questions/16440945/android-system-properties-unsetting-them-on-the-command-line

this one should be in ./data/property/persist.debug.atrace.boottrace
persist one are stayed even after reboot.

It used to start atrace during kernel boot (at least after zygote is up).

it's a bit strange from point of view that ftrace is always up

**Comment by littlewhywhat** [comment]
atrace is written in functional way with some global variables that makes it's hard to use. I will try to extract some basic functionality with refactoring
